// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyxvjwpxnhswvsjyxfok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5eHZqd3B4bmhzd3Zzanl4Zm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMTMxOTgsImV4cCI6MjA4NTU4OTE5OH0.ODv5IlAMV2PXkxIRpB-j1adnhjatD4peSVQscEPzy-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});